version = 1

test_patterns = [
  "tests/**",
  "bench/**"
]

exclude_patterns = [
  "examples/**",
  "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120

[[analyzers]]
name = "test-coverage"
enabled = true
